name: mon_frigo
description: Qu'est-ce qu'il y a dans mon frigo ?

publish_to: 'none'

version: 0.0.1+11

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.16.1
  collection: ^1.18.0
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_crashlytics: ^3.5.1 # No Windows
  firebase_messaging: ^14.8.1
  firebase_performance: ^0.9.4+1 # No Windows
  firebase_storage: ^11.7.1
  flutter: { sdk: flutter }
  flutter_local_notifications: ^17.0.0
  flutter_localizations: { sdk: flutter }
  flutter_native_splash: ^2.4.0
  fpdart: ^1.1.0
  go_router: ^14.0.2
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  rxdart: ^0.27.7
  share_plus: ^8.0.3

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: false # generate to Android Studio

  web:
    generate: true
    image_path: "assets/images/kitchen.png"
    theme_color: "#800020"

flutter_native_splash:
  color: "#FCF8F8"
  image: assets/images/kitchen.png
  color_dark: "#1C1C1C"
  image_dark: assets/images/kitchen.png