name: mon_frigo
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  file_picker: ^6.1.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.4 # No Windows
  firebase_messaging: ^14.7.4
  firebase_performance: ^0.9.3+3 # No Windows
  firebase_storage: ^11.5.1
  flutter: { sdk: flutter }
  flutter_local_notifications: ^16.1.0
  flutter_localizations: { sdk: flutter }
  flutter_web_plugins: { sdk: flutter }
  go_router: ^12.1.1
  google_sign_in: ^6.1.6
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
