name: mon_frigo
description: Qu'est-ce qu'il y a dans mon frigo ?

publish_to: 'none'

version: 0.0.1+11

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.16.1
  collection: ^1.17.2
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_auth: ^4.19.1
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.6 # No Windows
  firebase_messaging: ^14.7.6
  firebase_performance: ^0.9.3+5 # No Windows
  firebase_storage: ^11.6.11
  flutter: { sdk: flutter }
  flutter_local_notifications: ^17.0.0
  flutter_localizations: { sdk: flutter }
  fpdart: ^1.1.0
  go_router: ^13.2.2
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  rxdart: ^0.27.7
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
