name: mon_frigo
description: Qu'est-ce qu'il y a dans mon frigo ?

publish_to: 'none'

version: 0.0.1+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.6 # No Windows
  firebase_messaging: ^14.7.6
  firebase_performance: ^0.9.3+5 # No Windows
  firebase_storage: ^11.5.2
  flutter: { sdk: flutter }
  flutter_local_notifications: ^16.2.0
  flutter_localizations: { sdk: flutter }
  flutter_web_plugins: { sdk: flutter }
  fpdart: ^1.1.0
  go_router: ^12.1.1
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
