name: mon_frigo
description: Qu'est-ce qu'il y a dans mon frigo ?

publish_to: 'none'

version: 0.0.1+11

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.3
  collection: ^1.17.2
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.6 # No Windows
  firebase_messaging: ^14.7.6
  firebase_performance: ^0.9.3+5 # No Windows
  firebase_storage: ^11.5.2
  flutter: { sdk: flutter }
  flutter_local_notifications: ^17.0.0
  flutter_localizations: { sdk: flutter }
  flutter_native_splash: ^2.3.10
  fpdart: ^1.1.0
  go_router: ^13.0.1
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  rxdart: ^0.27.7
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/kitchen.png"

  android: false # generate to Android Studio

  web:
    generate: true
    image_path: "assets/images/kitchen.png"
    background_color: "#201a1b"
    theme_color: "#fffbff"

flutter_native_splash:
  color: "#fffbff"
  image: assets/images/kitchen.png
  color_dark: "#201a1b"