name: Intrégration continue

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter ${{ vars.FLUTTER_VERSION }}
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter analyze

  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Configure Signature
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties
          echo "${{ secrets.RELEASE_KEYSTORE }}" > upload-keystore.encoded
          base64 -d -i upload-keystore.encoded > ./android/app/keystore.jks
      - uses: actions/setup-java@v1.4.4
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter ${{ vars.FLUTTER_VERSION }}
      - name: Configure Flutter
        run: |
          flutter config --no-analytics
          flutter pub get
      - name: Build AppBundle Release
        run: flutter build appbundle --release
      - name: Push build to Releases
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "build-release"
          path: build/app/outputs/bundle/release/*.aab

  deploy:
    name: Deploy web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter ${{ vars.FLUTTER_VERSION }}
      - name: Configure Flutter
        run: |
          flutter config --no-analytics
          flutter pub get
      - name: Build Web Release
        run: flutter build web --release
      - name: Sync files FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.matthieudevilliers.fr
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/web/
          server-dir: /monfrigo.matthieudevilliers.fr/
